---

name: Git release action
description: GitHub action for tagging git semantic versions
branding:
  icon: bookmark
  color: green
inputs:
  use_prefix:
    description: If true, add "v" prefix to tags
    default: true
    required: false
  major:
    description: Major version number
    required: true
  minor:
    description: Minor version number
    required: true
  patch:
    description: Patch version number
    required: true
runs:
  using: composite
  steps:
    - name: Validate version inputs
      shell: bash
      run: |
        if [[ ! ${{ inputs.patch }} =~ ^[0-9]+$ ]]; then
          echo "Invalid patch version format. Expected a number."
          exit 1
        fi
        if [[ ! ${{ inputs.minor }} =~ ^[0-9]+$ ]]; then
          echo "Invalid patch version format. Expected a number."
          exit 1
        fi
        if [[ ! ${{ inputs.major }} =~ ^[0-9]+$ ]]; then
          echo "Invalid patch version format. Expected a number."
          exit 1
        fi
    - name: Tag semantic versions
      shell: bash
      run: |
        if [[ "${{ inputs.use_prefix }}" == "true" ]]; then
          prefix="v"
        else
          prefix=""
        fi
        major="${{ inputs.major }}"
        minor="${{ inputs.minor }}"
        patch="${{ inputs.patch }}"
        git tag -f "${prefix}${major}"
        git tag -f "${prefix}${major}.${minor}"
        git tag -f "${prefix}${major}.${minor}.${patch}"
    - name: Push tags
      shell: bash
      run: git push origin -f --tags
